### PR TITLE
Added support for scrollable target IDs.

### PR DESCRIPTION
**Pull request by Alex-231**
This is something I needed for a project, so I've been sitting on a fork for a while, but I thought someone else might appreciate this feature.

### CODE REVIEW

**Comment by ankeetmaini** [comment]
Thanks @Alex-231, but if you've id of the element can't you pass like below instead of handling in the component?

```jsx
<InfiniteScroll>
 scrollableTarget={document.getElementById('some-scrollable-id')}
```

**Comment by Alex-231** [comment]
No. I can't remember why though hah. I can only remember that I spent a lot of time trying a lot of things to avoid this solution. I'll have to take a look back and see why exactly this wouldn't work in my scenario.

**Comment by Alex-231** [comment]
I have a scrollable target divider containing my infinite scroll element.
I cannot reference this parent before it is rendered, and the infinite scroll inside needs to be rendered too. At least that's my understanding.

**Comment by Alex-231** [comment]
Using
```
<InfiniteScroll>
 scrollableTarget={document.getElementById('some-scrollable-id')}
```

causes the element to be undefined and therefore an error occurs when adding/removing the event listener.

**Comment by ankeetmaini** [comment]
Thanks for working on this, instead of adding a new prop, the `scrollableTarget` accepts `id` also. This was merged in #60

**Pull request closed without merging**
