### PR TITLE
Support threshold with units. e.g 100px, 80%...

### PR DESCRIPTION
**Pull request by vladik7244**

### CODE REVIEW

**Comment by vladik7244** [comment]
@ankeetmaini take a look, please

**Comment by ankeetmaini** [comment]
@vladik7244  Can you please update the Readme?

**Comment by vladik7244** [comment]
Sure

**Comment by ankeetmaini** [comment]
Thanks so much @vladik7244 . Released as react-infinite-scroll-component@4.2.0

**Pull request merged**
